name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: npm install
    - run: npm run lint
    - run: npm run build

    - name: Sync UI Bundle to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --include '*.zip'
      env:
        AWS_S3_BUCKET: ${{ secrets.DEVREL_ACCESS_KEY_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVREL_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: 'build'
        DEST_DIR: 'build'
      # if the AWS_S3_BUCKET is undefined, the task will fail
      # also make sure that we are on master before publishing the "latest" version
      if: ${{ env.AWS_S3_BUCKET != '' && github.ref == 'refs/heads/master' }}
